CONFIG_GPIO=y
CONFIG_CD4067=y
CONFIG_CRC=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_I2C=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_PWM=y
CONFIG_SERIAL=y
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVERS=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_USE_DT_CODE_PARTITION=y

# USB MIDI
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_MIDI2_CLASS=y
CONFIG_MIDI2_UMP_STREAM_RESPONDER=y
CONFIG_UDC_STM32=y
CONFIG_USBD_THREAD_STACK_SIZE=4096
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y
